### ISSUE TITLE
[팀 회고] _ 레포지토리 삭제에 대한 회고

### ISSUE THREAD

**Issue by Lpickle** [codestates/MARE#99]
### github 회고

---

### 1. 사건의 경위

- 아침 일찍 KPT 회고 작성 및 제출을 위해 깃허브 _ 팀프로젝트 사이트에 접속했는데 404 에러가 났었습니다.
    
    처음에는 간단한 인터넷 이슈인가 했는데 인터넷 문제는 아니였고, 제 깃허브 아이디 문제인가 해서 재접속 을 시도 하였지만 큰 반응이 없어 팀원들과 이슈를 공유 했습니다. 팀원들도 똑같은 문제였고 문제를 찾기위해 모두 검색을 하며 해결하려 했습니다. 
    
    진행 중 레포지토리가 삭제가 되었다는 걸 깨닳았고, 팀 원 개개인의 깃허브 셋팅을 확인해서 레포지토리 삭제 내역을 확인을 했지만, 그 당시 확인결과, 팀에서는 삭제 한 내역을 발견할 수 없었습니다.
    
    그래서 방법을 찾으며, 엔지니어님께 이슈셰어링을 하였고 엔지니어님께서 직접 깃허브에 메일을 보낸 결과 저희 쪽에서 삭제되었다는 결론이 났습니다.
    

### 2.  팀에서는 삭제 한 내역을 발견할 수 없었습니다. ?

- 팀원 한 명씩 레포지토리 삭제 내역을 체크 했었습니다. 한 명의 레포지토리 삭제내역에 팀프로젝트 레포지토리가 있었지만, 그 레포지토리는 며칠전 포크를 했다 지운 레포지토리였고 (사건 발생보다 훨씬 앞), “ forked from “ 도 codestatus 가 적혀않았습니다. 또한 초반 프로젝트 당시 포크 후 삭제 한 것이라 삭제한 시간도 사건 날짜가 적혀있지 않아 당연히 그건 아니라고 생각했습니다.

### 3. 이렇게 된 이유

1. 커뮤니케이션에 대한 아쉬움
    1. 2번 _ 팀에서는 삭제 한 내역을 발견할 수 없었다. 처럼 팀원들의 삭제 내역에선 정말 저희가 확인할 수 없었고, 삭제에 관련된 이슈를 공유해 준 팀원이 없었습니다.  
2. 깃 미숙함
    1. 업데이트가 있을때 자유자제로 pull, push 를 이용을 하기보단, fork 를 끊고 다시 fork 를 해서 업데이트를 했었습니다 ( 초반에 ) 그로인해 이 문제가 발생되었다고 생각이 듭니다. 
3. 편의성을 위해 전부가 admin 이였습니다.
    1. 초반에 전부를 admin 권한으로 바꿨었습니다. 이유는 admin 을 바꿔 WIKI 수정을 다 같이 빠르고,자유롭게 하기 위함 이였습니다. 돌이켜보면 전부다 할 수 있어서 비교적 조심스러워야할 부분을 좀 덜 신중하지 않았나 하는 생각이 듭니다. 

### 4. 앞으로? ( 해결방안 )

1. 커뮤니케이션
    1. 문제가 발생했을때, 본인과 연관이 있다고 생각하면 두려워하지말고 바로바로 공유해주기
        1. 바로바로 공유를 하지않게되면 문제에 원인을 찾는 시간이 길어지기 때문에 바로 공유하기.
2. 깃 익히기
    1. 깃 사용중 확실하지 않으면 무조건 팀원들과 공유를 하며 해결하기 
3. 팀장만 admin 권한 부여받기
    1. 편의성을 위해 전부다 admin을 했었는데, 앞으로는 팀장만 admin 으로써 좀 더 신중하게 관리하겠습니다.

**Comment by wnstjr0317** [comment]
@Lpickle 회고를 꼼꼼히 잘 작성해주셨습니다. 이번 삭제 건으로 오버커뮤니케이션의 중요성을 느끼셨을거라 생각합니다. 파이널프로젝트에서 동일한 문제 , 다른 문제가 발생하지 않도록 더 많은 커뮤니케이션을 신경써주세요 ;) 고생하셨습니다~!
